<?php

namespace GestVeterinaireBundle\Repository;

/**
 * CategorieEspecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEspecesRepository extends \Doctrine\ORM\EntityRepository
{

	 public function idEspece($laEspece)
    {
        $qb=$this->createQueryBuilder('p');
        $qb->where('p.libelleEspece =:libelleEspece');
        $qb->setParameter('libelleEspece', $laEspece);
        return $qb->getQuery()->getResult();
    }
}
