<?php

namespace GestVeterinaireBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	// Liste toutes les commandes d'un vétérinaire (qui sera choisi au préalable par l'utilisateur)
	public function commandesVeterinaire($idVetUrl)
	{
		$requete = $this->createQueryBuilder('CR');
		$requete->where('CR.leVeterinaire = :idEnParam')->setParameter('idEnParam', $idVetUrl);

		return $requete->getQuery()->getResult();
	}
}
