<?php

namespace GestVeterinaireBundle\Repository;

/**
 * ProduitVeterinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitVeterinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
