<?php

namespace GestVeterinaireBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{

	 public function idRegion($laRegion)
    {
        $qb=$this->createQueryBuilder('p');
        $qb->where('p.libelleRegion =:libelleRegion');
        $qb->setParameter('libelleRegion', $laRegion);
        return $qb->getQuery()->getResult();
    }
}
