<?php

namespace GestVeterinaireBundle\Repository;

/**
 * TypeEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEtablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
