<?php

namespace GestVeterinaireBundle\Repository;

/**
 * VeterinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeterinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
