<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPqug2k5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPqug2k5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPqug2k5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPqug2k5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPqug2k5\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pqug2k5',
    'container.build_id' => 'd53367cd',
    'container.build_time' => 1527785708,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPqug2k5');
