<?php

namespace Proxies\__CG__\GestVeterinaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EnvoiEchantillon extends \GestVeterinaireBundle\Entity\EnvoiEchantillon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'id', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'dateDemande', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'dateLivraison', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'qteLivree', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'leProduitVeterinaire', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'leVeterinaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'id', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'dateDemande', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'dateLivraison', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'qteLivree', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'leProduitVeterinaire', '' . "\0" . 'GestVeterinaireBundle\\Entity\\EnvoiEchantillon' . "\0" . 'leVeterinaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EnvoiEchantillon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDemande($dateDemande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDemande', [$dateDemande]);

        return parent::setDateDemande($dateDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDemande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDemande', []);

        return parent::getDateDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateLivraison($dateLivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateLivraison', [$dateLivraison]);

        return parent::setDateLivraison($dateLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateLivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateLivraison', []);

        return parent::getDateLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteLivree($qteLivree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteLivree', [$qteLivree]);

        return parent::setQteLivree($qteLivree);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteLivree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteLivree', []);

        return parent::getQteLivree();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeProduitVeterinaire(\GestVeterinaireBundle\Entity\ProduitVeterinaire $leProduitVeterinaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeProduitVeterinaire', [$leProduitVeterinaire]);

        return parent::setLeProduitVeterinaire($leProduitVeterinaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeProduitVeterinaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeProduitVeterinaire', []);

        return parent::getLeProduitVeterinaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeVeterinaire(\GestVeterinaireBundle\Entity\Veterinaire $leVeterinaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeVeterinaire', [$leVeterinaire]);

        return parent::setLeVeterinaire($leVeterinaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeVeterinaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeVeterinaire', []);

        return parent::getLeVeterinaire();
    }

}
