<?php

namespace Proxies\__CG__\GestVeterinaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CommandeProduitVeterinaire extends \GestVeterinaireBundle\Entity\CommandeProduitVeterinaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'id', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'qteCommandee', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'laCommande', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'leProduitVeterinaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'id', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'qteCommandee', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'laCommande', '' . "\0" . 'GestVeterinaireBundle\\Entity\\CommandeProduitVeterinaire' . "\0" . 'leProduitVeterinaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CommandeProduitVeterinaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQteCommandee($qteCommandee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQteCommandee', [$qteCommandee]);

        return parent::setQteCommandee($qteCommandee);
    }

    /**
     * {@inheritDoc}
     */
    public function getQteCommandee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQteCommandee', []);

        return parent::getQteCommandee();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaCommande(\GestVeterinaireBundle\Entity\Commande $laCommande = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaCommande', [$laCommande]);

        return parent::setLaCommande($laCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaCommande', []);

        return parent::getLaCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeProduitVeterinaire(\GestVeterinaireBundle\Entity\ProduitVeterinaire $leProduitVeterinaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeProduitVeterinaire', [$leProduitVeterinaire]);

        return parent::setLeProduitVeterinaire($leProduitVeterinaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeProduitVeterinaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeProduitVeterinaire', []);

        return parent::getLeProduitVeterinaire();
    }

}
