<?php

namespace Proxies\__CG__\GestVeterinaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DelegueVeterinaire extends \GestVeterinaireBundle\Entity\DelegueVeterinaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'id', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'nomDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'prenomDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'telDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'mailDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'lesCategorieEspeces', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'laRegion'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'id', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'nomDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'prenomDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'telDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'mailDelegue', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'lesCategorieEspeces', '' . "\0" . 'GestVeterinaireBundle\\Entity\\DelegueVeterinaire' . "\0" . 'laRegion'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DelegueVeterinaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDelegue($nomDelegue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDelegue', [$nomDelegue]);

        return parent::setNomDelegue($nomDelegue);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDelegue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDelegue', []);

        return parent::getNomDelegue();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomDelegue($prenomDelegue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomDelegue', [$prenomDelegue]);

        return parent::setPrenomDelegue($prenomDelegue);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomDelegue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomDelegue', []);

        return parent::getPrenomDelegue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelDelegue($telDelegue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelDelegue', [$telDelegue]);

        return parent::setTelDelegue($telDelegue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelDelegue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelDelegue', []);

        return parent::getTelDelegue();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailDelegue($mailDelegue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailDelegue', [$mailDelegue]);

        return parent::setMailDelegue($mailDelegue);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailDelegue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailDelegue', []);

        return parent::getMailDelegue();
    }

    /**
     * {@inheritDoc}
     */
    public function addUneCategorieEspece(\GestVeterinaireBundle\Entity\CategorieEspeces $uneCategorieEspece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUneCategorieEspece', [$uneCategorieEspece]);

        return parent::addUneCategorieEspece($uneCategorieEspece);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUneCategorieEspece(\GestVeterinaireBundle\Entity\CategorieEspeces $uneCategorieEspece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUneCategorieEspece', [$uneCategorieEspece]);

        return parent::removeUneCategorieEspece($uneCategorieEspece);
    }

    /**
     * {@inheritDoc}
     */
    public function getLesCategorieEspeces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLesCategorieEspeces', []);

        return parent::getLesCategorieEspeces();
    }

    /**
     * {@inheritDoc}
     */
    public function setLaRegion(\GestVeterinaireBundle\Entity\Region $laRegion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLaRegion', [$laRegion]);

        return parent::setLaRegion($laRegion);
    }

    /**
     * {@inheritDoc}
     */
    public function getLaRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLaRegion', []);

        return parent::getLaRegion();
    }

}
